import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { cn } from "@/lib/utils";
import type { Message } from "@/lib/sarvis";
import sarvisLogo from "@/assets/sarvis-logo.png";
import { Button } from "@/components/ui/button";
import { Code2, Download, Copy, Volume2, Check } from "lucide-react";
import type { CanvasContent } from "@/components/CodeCanvas";
import { NewsCards } from "@/components/NewsCards";
import { useState } from "react";
import { toast } from "sonner";
import { speakWithMaleVoice } from "@/lib/voice";

interface MessageBubbleProps {
  message: Message;
  streaming?: boolean;
  onOpenCanvas?: (content: CanvasContent) => void;
}

// Strip any stray "(pronounced ...)" hints the model might still add.
const stripPronunciationHints = (text: string): string =>
  text
    .replace(/\s*[([]\s*pronounced[^)\]]*[)\]]/gi, "")
    .replace(/[,–—-]\s*pronounced[^.,!?\n]*/gi, "")
    .replace(/\bS[\s.\-_]*A[\s.\-_]*R[\s.\-_]*V[\s.\-_]*I[\s.\-_]*S\b/gi, "SARVIS");

export const MessageBubble = ({ message, streaming, onOpenCanvas }: MessageBubbleProps) => {
  const isUser = message.role === "user";
  const [copied, setCopied] = useState(false);

  const displayContent = isUser ? message.content : stripPronunciationHints(message.content);

  const handleCopy = () => {
    navigator.clipboard.writeText(displayContent);
    setCopied(true);
    toast.success("Copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSpeak = () => {
    void speakWithMaleVoice(displayContent);
  };

  if (isUser) {
    return (
      <div className="flex w-full justify-end animate-in fade-in slide-in-from-bottom-2 duration-200">
        <div className="max-w-[90%] sm:max-w-[85%] rounded-3xl bg-bubble-user px-3.5 sm:px-4 py-2.5 text-[14px] sm:text-[15px] leading-relaxed text-bubble-user-foreground whitespace-pre-wrap break-words">
          {message.content}
        </div>
      </div>
    );
  }

  return (
    <div className="flex w-full gap-4 animate-in fade-in slide-in-from-bottom-2 duration-200">
      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-primary/40 bg-background shadow-sm overflow-hidden glow-ring">
        <img src={sarvisLogo} alt="SARVIS" className="h-full w-full object-cover" />
      </div>

      <div className="flex-1 min-w-0 space-y-2 pt-0.5">
        {message.imageUrl && (
          <div className="space-y-2">
            <div className="not-prose rounded-xl border border-border bg-secondary/20 p-3 inline-flex">
              <img
                src={message.imageUrl}
                alt="Generated by SARVIS"
                className="max-h-96 w-auto rounded-lg"
                loading="lazy"
              />
            </div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                const link = document.createElement("a");
                link.href = message.imageUrl;
                link.download = `sarvis-image-${Date.now()}.png`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
              }}
              className="gap-2"
            >
              <Download className="h-4 w-4" />
            </Button>
          </div>
        )}
        {message.news && (
          <NewsCards articles={message.news.articles} query={message.news.query} />
        )}
        {displayContent && (
          <div className="group relative">
            <div
              className={cn(
                "prose prose-sm max-w-none text-[15px] leading-relaxed p-4 rounded-2xl border border-border bg-card shadow-sm",
                "dark:prose-invert",
                "prose-p:my-2 prose-p:text-foreground",
                "prose-headings:text-foreground prose-strong:text-foreground",
                "prose-code:text-foreground prose-code:bg-muted prose-code:rounded prose-code:px-1 prose-code:py-0.5",
                "prose-code:before:content-[''] prose-code:after:content-['']",
                "prose-pre:bg-muted prose-pre:border prose-pre:border-border prose-pre:rounded-xl",
                "prose-a:text-foreground prose-a:underline prose-a:underline-offset-2",
              )}
            >
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  pre: ({ children, ...props }) => {
                    const childArray = Array.isArray(children) ? children : [children];
                    // eslint-disable-next-line @typescript-eslint/no-explicit-any
                    const codeEl: any = childArray.find((c: any) => c && typeof c === "object");
                    const className: string = codeEl?.props?.className ?? "";
                    const langMatch = /language-([\w-]+)/.exec(className);
                    const language = langMatch?.[1];
                    const raw = String(codeEl?.props?.children ?? "").replace(/\n$/, "");

                    return (
                      <div className="not-prose group relative my-3 overflow-hidden rounded-xl border border-border bg-muted">
                        <div className="flex items-center justify-between border-b border-border bg-secondary/40 px-3 py-1.5">
                          <span className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
                            {language ?? "code"}
                          </span>
                          {onOpenCanvas && (
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              onClick={() =>
                                onOpenCanvas({
                                  kind: "code",
                                  code: raw,
                                  language,
                                  title: language ? `${language} snippet` : "Code snippet",
                                })
                              }
                              className="h-7 gap-1.5 px-2 text-xs"
                            >
                              <Code2 className="h-3.5 w-3.5" />
                              Open in canvas
                            </Button>
                          )}
                        </div>
                        <pre
                          {...props}
                          className="m-0 overflow-x-auto bg-transparent p-3 text-[13px] leading-relaxed"
                        >
                          <code className={className}>{raw}</code>
                        </pre>
                      </div>
                    );
                  },
                }}
              >
                {displayContent}
              </ReactMarkdown>
              {streaming && (
                <span className="ml-0.5 inline-block h-4 w-1 animate-pulse rounded-sm bg-foreground align-middle" />
              )}
            </div>
            
            {/* Action buttons under the box */}
            <div className="flex items-center gap-2 mt-2 opacity-0 group-hover:opacity-100 transition-opacity">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopy}
                className="h-8 px-2 text-xs gap-1.5 text-muted-foreground hover:text-foreground"
              >
                {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                {copied ? "Copied" : "Copy"}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleSpeak}
                className="h-8 px-2 text-xs gap-1.5 text-muted-foreground hover:text-foreground"
              >
                <Volume2 className="h-3.5 w-3.5" />
                Speak
              </Button>
            </div>
          </div>
        )}
        {!message.content && streaming && (
          <div className="flex items-center gap-1.5 pt-1">
            <span className="h-2 w-2 animate-bounce rounded-full bg-muted-foreground" style={{ animationDelay: "0ms" }} />
            <span className="h-2 w-2 animate-bounce rounded-full bg-muted-foreground" style={{ animationDelay: "150ms" }} />
            <span className="h-2 w-2 animate-bounce rounded-full bg-muted-foreground" style={{ animationDelay: "300ms" }} />
          </div>
        )}
      </div>
    </div>
  );
};
